AWSTemplateFormatVersion: '2010-09-09'
Description: Knit Bingo backend (Lambda Function URL + DynamoDB + SES)

Parameters:
  LambdaCodeBucket:
    Type: String
    Default: bingoknitting-artifacts
  LambdaCodeKey:
    Type: String
    Default: backend/lambda.zip
  SESFromAddress:
    Type: String
    Default: hello@nubrajarial.com

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  CommunityCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: communitycards
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  MagicLinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: magiclink
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  ApiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDbAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Scan
                Resource:
                  - !GetAtt UserTable.Arn
                  - !GetAtt CommunityCardsTable.Arn
                  - !GetAtt MagicLinkTable.Arn
        - PolicyName: SesSendEmail
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: '*'

  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: knit-bingo-api
      Runtime: python3.12
      Handler: handler.handler
      Timeout: 10
      MemorySize: 256
      Role: !GetAtt ApiFunctionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Environment:
        Variables:
          USER_TABLE: !Ref UserTable
          COMMUNITY_CARDS_TABLE: !Ref CommunityCardsTable
          MAGIC_LINK_TABLE: !Ref MagicLinkTable
          SES_FROM_ADDRESS: !Ref SESFromAddress

  ApiFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt ApiFunction.Arn
      AuthType: NONE
      Cors:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'

  ApiFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

Outputs:
  FunctionUrl:
    Value: !GetAtt ApiFunctionUrl.FunctionUrl
  UserTableName:
    Value: !Ref UserTable
  CommunityCardsTableName:
    Value: !Ref CommunityCardsTable